[package]
name = "screenshot_utility"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui = "0.22.0"
global-hotkey = "0.2.3"
image = "0.24.6"
screenshots = "0.7.0"
